common: &common
  adapter: postgresql
  pool: 10

development:
  <<: *common
  database: slashify_development
  host: localhost

test:
  <<: *common
  database: slashify_test
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
